### PR TITLE
Fix Galaxypedia API endpoint returning incorrect ship cost information

### PR DESCRIPTION
**Pull request by SeaswimmerTheFsh**
image

### CODE REVIEW

**Comment by Wingysam** [comment]
Why shouldn't the Galaxypedia endpoint return ExtraMaterials?

**Comment by SeaswimmerTheFsh** [comment]
Only Ketchupbot uses the Galaxypedia endpoint, so nothing is broken by removing this. Also, the functionality is broken (see screenshot in original post)/

**Comment by Wingysam** [comment]
Wouldn't Ketchupbot be broken by removing its datasource? Why shouldn't the bot update the ExtraMaterials requirements? Isn't up-to-date ExtraMaterials data in the database?

**Comment by SeaswimmerTheFsh** [comment]
sugondese has stated already that ketchupbot isn't broken by this change. This issue would also be fixed if extramaterials were accurate, but they don't appear to be?

**Comment by SeaswimmerTheFsh** [comment]
update: its not broken, someone gave annihilator extramaterials for some reason??
image

**Pull request closed without merging**
